### PR TITLE
feat: Support Firebase 8.0.0

### PR DESCRIPTION
**Pull request by MarcARoberge**
Added support for Firebase 8.0.0 definitions change

_First PR here, let me know if you are not ok with anything :)_

### CODE REVIEW

**Comment by MarcARoberge** [comment]
This is breaking changes. This might need a big version update. I'll let you decide what to do with that.

**Comment by zkhalapyan** [comment]
Hey folks, doesn't seem like the current library compiles without this change. Had two questions for you:

1. What prevents this from getting merged in? The coveralls error may be an intermittent issue (i.e. run again, should succeed?)
2. Any workarounds to resolve https://github.com/MichaelSolati/geofirestore-core/issues/3 while I wait? May use this git repo/pull request as an NPM package source?

**Comment by zkhalapyan** [comment]
@MarcARoberge also, can you rebase your pull request? Seems like it's currently 8 commits behind main.

**Comment by MichaelSolati** [comment]
Hey @MarcARoberge thank you for submitting this PR. Technically everything you did was good, the only problem was that it would stop "supporting" firebase 6 and 7. I actually created a fix before I looked at this PR (so I'm sorry you did the work without me using it, but thank you for putting in the work).

**Comment by MarcARoberge** [comment]
Hey ! Sorry for my late response, did not received any notifications ! No problem at all, it is a great project !

**Pull request closed without merging**
